glbinding: glbinding::AbstractFunction Class Reference
glbinding::AbstractFunction Class Reference
The AbstractFunction represents an OpenGL API function.
#include <glbinding/include/glbinding/AbstractFunction.h>
Classes
struct State
The State struct represents the configuration of an OpenGL function for one thread. This includes the driver function pointer (is allowed to differ between contexts) and the callback mask.
Public Member Functions
AbstractFunction (const char *name)
Constructor.
virtual ~AbstractFunction ()
Destructor to guarantee correct memory deallocation of subclasses.
const char * name () const
Name accessor.
void resolveAddress ()
Lookup the function pointer and stores it in the current state.
bool isResolved () const
Check for a valid function pointer in the current state.
ProcAddress address () const
Function pointer accessor.
CallbackMask callbackMask () const
Callback mask accessor.
void setCallbackMask (CallbackMask mask)
Reconfigures the callback mask for the current state.
void addCallbackMask (CallbackMask mask)
Reconfigures the callback mask for the current state in means of a bit-wise 'or' operation with the current callback mask.
void removeCallbackMask (CallbackMask mask)
Reconfigures the callback mask for the current state in means of a bit-wise 'clear' operation of the current callback mask.
bool isEnabled (CallbackMask mask) const
Check if all bits of the parameter are set in the currently configured callback mask of the current state.
bool isAnyEnabled (CallbackMask mask) const
Check if any bit of the parameter is set in the currently configured callback mask of the current state.
void unresolved () const
Triggers a call of the unresolved callback.
void before (const FunctionCall &call) const
Triggers a call of the before callback, passing the parameters.
void after (const FunctionCall &call) const
Triggers a call of the after callback, passing the parameters and return value.
Protected Member Functions
bool hasState () const
Checks for existance of the current configured state.
bool hasState (int pos) const
Checks for existance of a state.
State & state () const
Current state accessor.
State & state (int pos) const
State accessor.
Static Protected Member Functions
static void provideState (int pos)
Extend the function states to include the state identified through pos.
static void neglectState (int pos)
Reconfigures the states so that the state identified through pos is neglected.
static void setStatePos (int pos)
Updates the currently used state.
Protected Attributes
const char * m_name
The OpenGL API function name, including the 'gl' prefix.
std::vector< State > m_states
The list of all states.
Static Protected Attributes
static int s_maxpos
The global maximum of states per function.
Friends
class Binding
For state configuration.
Detailed Description
The AbstractFunction represents an OpenGL API function.
Constructor & Destructor Documentation
glbinding::AbstractFunction::AbstractFunction (const char * name)
Constructor.
Parameters
[in] name The actual exported OpenGL API function name, including the 'gl' prefix.
virtual glbinding::AbstractFunction::~AbstractFunction () virtual
Destructor to guarantee correct memory deallocation of subclasses.
Member Function Documentation
const char* glbinding::AbstractFunction::name () const
Name accessor.
Returns
The function name.
void glbinding::AbstractFunction::resolveAddress ()
Lookup the function pointer and stores it in the current state.
bool glbinding::AbstractFunction::isResolved () const
Check for a valid function pointer in the current state.
Returns
true iff a valid function pointer is stored in the current state.
ProcAddress glbinding::AbstractFunction::address () const
Function pointer accessor.
Returns
The function pointer.
Referenced by glbinding::Function< ReturnType, Arguments >::call().
CallbackMask glbinding::AbstractFunction::callbackMask () const
Callback mask accessor.
Returns
Returns the currently configured callback mask for the current state.
void glbinding::AbstractFunction::setCallbackMask (CallbackMask mask)
Reconfigures the callback mask for the current state.
Parameters
[in] mask The new callback mask.
void glbinding::AbstractFunction::addCallbackMask (CallbackMask mask)
Reconfigures the callback mask for the current state in means of a bit-wise 'or' operation with the current callback mask.
Parameters
[in] mask The callback mask to include.
void glbinding::AbstractFunction::removeCallbackMask (CallbackMask mask)
Reconfigures the callback mask for the current state in means of a bit-wise 'clear' operation of the current callback mask.
Parameters
[in] mask The callback mask to exclude.
bool glbinding::AbstractFunction::isEnabled (CallbackMask mask) const
Check if all bits of the parameter are set in the currently configured callback mask of the current state.
Parameters
[in] mask The mask to check against.
Returns
true iff all bits are set.
Referenced by glbinding::Function< ReturnType, Arguments >::call().
bool glbinding::AbstractFunction::isAnyEnabled (CallbackMask mask) const
Check if any bit of the parameter is set in the currently configured callback mask of the current state.
Parameters
[in] mask The mask to check against.
Returns
true iff at least one bit is set.
Referenced by glbinding::Function< ReturnType, Arguments >::call().
void glbinding::AbstractFunction::unresolved () const
Triggers a call of the unresolved callback.
Referenced by glbinding::Function< ReturnType, Arguments >::call().
void glbinding::AbstractFunction::before (const FunctionCall & call) const
Triggers a call of the before callback, passing the parameters.
Parameters
[in] call The parameters of the current function call.
void glbinding::AbstractFunction::after (const FunctionCall & call) const
Triggers a call of the after callback, passing the parameters and return value.
Parameters
[in] call The parameters and the return value of the current function call.
bool glbinding::AbstractFunction::hasState () const protected
Checks for existance of the current configured state.
Returns
true iff the current state still exists.
This method is usually used to detect invalid state clean up.
bool glbinding::AbstractFunction::hasState (int pos) const protected
Checks for existance of a state.
Parameters
[in] pos The index of the state to check.
Returns
true iff the state exists.
State& glbinding::AbstractFunction::state () const protected
Current state accessor.
Returns
The current state
State& glbinding::AbstractFunction::state (int pos) const protected
State accessor.
Parameters
[in] pos The index of the state
Returns
The state
static void glbinding::AbstractFunction::provideState (int pos) static protected
Extend the function states to include the state identified through pos.
Parameters
pos The index of the state to provide.
static void glbinding::AbstractFunction::neglectState (int pos) static protected
Reconfigures the states so that the state identified through pos is neglected.
Parameters
pos The index of the state to neglect.
static void glbinding::AbstractFunction::setStatePos (int pos) static protected
Updates the currently used state.
Parameters
pos The index of the new state.
Friends And Related Function Documentation
friend class Binding friend
For state configuration.
Member Data Documentation
const char* glbinding::AbstractFunction::m_name protected
The OpenGL API function name, including the 'gl' prefix.
std::vector<State> glbinding::AbstractFunction::m_states mutable protected
The list of all states.
int glbinding::AbstractFunction::s_maxpos static protected
The global maximum of states per function.
The documentation for this class was generated from the following file:
AbstractFunction.h