glbinding: glbinding Namespace Reference
glbinding Namespace Reference
Contains all the classes of glbinding.
Namespaces
logging
Classes
class AbstractFunction
class AbstractValue
class Binding
struct CallbackType
struct CallbackType< void, Arguments... >
class ContextInfo
class Function
struct FunctionCall
struct FunctionHelper
struct FunctionHelper< void, Arguments... >
struct intersect_SharedBitfield
struct intersect_SharedBitfield< SharedBitfield< T, Types... >, SharedBitfield< OtherTypes... > >
struct is_member_of_SharedBitfield
struct is_member_of_SharedBitfield< T, U, Types... >
class Meta
struct prepend_to_SharedBitfield
struct prepend_to_SharedBitfield< T, SharedBitfield< Types... > >
class SharedBitfield
class SharedBitfield< Type >
class SharedBitfield< Type, Types... >
class SharedBitfield<>
class SharedBitfieldBase
class Value
struct ValueAdder
struct ValueAdder< Argument, Arguments... >
struct ValueAdder<>
class Version
The Version class represents a OpenGL version, consisting of majow version and minor version, excluding the profile information.
Typedefs
using SimpleFunctionCallback = std::function< void(const AbstractFunction &)>
using FunctionCallback = std::function< void(const FunctionCall &)>
using ContextHandle = long long
using ProcAddress) = void(*)(
Enumerations
enum CallbackMask : unsigned char {
CallbackMask::None = 0, CallbackMask::Unresolved = 1 << 0, CallbackMask::Before = 1 << 1, CallbackMask::After = 1 << 2,
CallbackMask::Parameters = 1 << 3, CallbackMask::ReturnValue = 1 << 4, CallbackMask::Logging = 1 << 5, CallbackMask::ParametersAndReturnValue = Parameters | ReturnValue,
CallbackMask::BeforeAndAfter = Before | After
}
Functions
GLBINDING_API CallbackMask operator| (CallbackMask a, CallbackMask b)
GLBINDING_API CallbackMask operator~ (CallbackMask a)
GLBINDING_API CallbackMask operator& (CallbackMask a, CallbackMask b)
GLBINDING_API CallbackMask & operator|= (CallbackMask &a, CallbackMask b)
GLBINDING_API CallbackMask & operator&= (CallbackMask &a, CallbackMask b)
GLBINDING_API void setCallbackMask (CallbackMask mask)
GLBINDING_API void setCallbackMaskExcept (CallbackMask mask, const std::set< std::string > &blackList)
GLBINDING_API void addCallbackMask (CallbackMask mask)
GLBINDING_API void addCallbackMaskExcept (CallbackMask mask, const std::set< std::string > &blackList)
GLBINDING_API void removeCallbackMask (CallbackMask mask)
GLBINDING_API void setUnresolvedCallback (SimpleFunctionCallback callback)
GLBINDING_API void setBeforeCallback (FunctionCallback callback)
GLBINDING_API void setAfterCallback (FunctionCallback callback)
GLBINDING_API ContextHandle getCurrentContext ()
GLBINDING_API ProcAddress getProcAddress (const char *name)
template<typename Enum , typename ConvertibleEnum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator| (Enum a, ConvertibleEnum b)
template<typename ConvertibleEnum , typename Enum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator| (ConvertibleEnum a, Enum b)
template<typename Enum , typename ConvertibleEnum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator|= (Enum &a, ConvertibleEnum b)
template<typename Enum , typename ConvertibleEnum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator& (Enum a, ConvertibleEnum b)
template<typename ConvertibleEnum , typename Enum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator& (ConvertibleEnum a, Enum b)
template<typename Enum , typename ConvertibleEnum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator&= (Enum &a, ConvertibleEnum b)
template<typename Enum , typename ConvertibleEnum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator^ (Enum a, ConvertibleEnum b)
template<typename ConvertibleEnum , typename Enum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator^ (ConvertibleEnum a, Enum b)
template<typename Enum , typename ConvertibleEnum >
std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type operator^= (Enum &a, ConvertibleEnum b)
template<typename Argument >
AbstractValue * createValue (Argument argument)
template<typename... Arguments>
std::vector< AbstractValue * > createValues (Arguments &&...arguments)
template<typename... Arguments>
void addValuesTo (std::vector< glbinding::AbstractValue * > &values, Arguments &&...arguments)
Detailed Description
Contains all the classes of glbinding.
TODO: Detailed documentation for glbinding here.
Typedef Documentation
using glbinding::SimpleFunctionCallback = typedef std::function<void(const AbstractFunction &)>
using glbinding::FunctionCallback = typedef std::function<void(const FunctionCall &)>
using glbinding::ContextHandle = typedef long long
using glbinding::ProcAddress = typedef void(*)(
Enumeration Type Documentation
enum glbinding::CallbackMask : unsigned char strong
Enumerator
None
Unresolved
Before
After
Parameters
ReturnValue
Logging
ParametersAndReturnValue
BeforeAndAfter
Function Documentation
GLBINDING_API CallbackMask glbinding::operator| (CallbackMask a, CallbackMask b)
GLBINDING_API CallbackMask glbinding::operator~ (CallbackMask a)
GLBINDING_API CallbackMask glbinding::operator& (CallbackMask a, CallbackMask b)
GLBINDING_API CallbackMask& glbinding::operator|= (CallbackMask & a, CallbackMask b)
GLBINDING_API CallbackMask& glbinding::operator&= (CallbackMask & a, CallbackMask b)
GLBINDING_API void glbinding::setCallbackMask (CallbackMask mask)
GLBINDING_API void glbinding::setCallbackMaskExcept (CallbackMask mask, const std::set< std::string > & blackList)
GLBINDING_API void glbinding::addCallbackMask (CallbackMask mask)
GLBINDING_API void glbinding::addCallbackMaskExcept (CallbackMask mask, const std::set< std::string > & blackList)
GLBINDING_API void glbinding::removeCallbackMask (CallbackMask mask)
GLBINDING_API void glbinding::setUnresolvedCallback (SimpleFunctionCallback callback)
GLBINDING_API void glbinding::setBeforeCallback (FunctionCallback callback)
GLBINDING_API void glbinding::setAfterCallback (FunctionCallback callback)
GLBINDING_API ContextHandle glbinding::getCurrentContext ()
GLBINDING_API ProcAddress glbinding::getProcAddress (const char * name)
template<typename Enum , typename ConvertibleEnum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator| (Enum a, ConvertibleEnum b)
template<typename ConvertibleEnum , typename Enum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator| (ConvertibleEnum a, Enum b)
template<typename Enum , typename ConvertibleEnum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator|= (Enum & a, ConvertibleEnum b)
template<typename Enum , typename ConvertibleEnum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator& (Enum a, ConvertibleEnum b)
template<typename ConvertibleEnum , typename Enum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator& (ConvertibleEnum a, Enum b)
template<typename Enum , typename ConvertibleEnum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator&= (Enum & a, ConvertibleEnum b)
template<typename Enum , typename ConvertibleEnum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator^ (Enum a, ConvertibleEnum b)
template<typename ConvertibleEnum , typename Enum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator^ (ConvertibleEnum a, Enum b)
template<typename Enum , typename ConvertibleEnum > std::enable_if< std::is_base_of< SharedBitfieldBase< typename std::underlying_type< typename std::enable_if< std::is_enum< Enum >::value, Enum >::type >::type >, ConvertibleEnum >::value, Enum >::type glbinding::operator^= (Enum & a, ConvertibleEnum b)
template<typename Argument > AbstractValue * glbinding::createValue (Argument argument)
Referenced by glbinding::FunctionHelper< ReturnType, Arguments >::call().
template<typename... Arguments> std::vector< AbstractValue * > glbinding::createValues (Arguments &&... arguments)
References addValuesTo().
Referenced by glbinding::FunctionHelper< ReturnType, Arguments >::call(), and glbinding::FunctionHelper< void, Arguments... >::call().
template<typename... Arguments> void glbinding::addValuesTo (std::vector< glbinding::AbstractValue * > & values, Arguments &&... arguments)
Referenced by createValues().