glbinding: glbinding::FunctionHelper< void, Arguments... > Struct Template Reference
glbinding::FunctionHelper< void, Arguments... > Struct Template Reference
#include <glbinding/include/glbinding/Function.hpp>
Public Member Functions
void call (const glbinding::Function< void, Arguments... > *function, Arguments &&...arguments) const
void basicCall (const glbinding::Function< void, Arguments... > *function, Arguments &&...arguments) const
Member Function Documentation
template<typename... Arguments> void glbinding::FunctionHelper< void, Arguments... >::call (const glbinding::Function< void, Arguments... > * function, Arguments &&... arguments) const inline
References glbinding::After, glbinding::FunctionHelper< ReturnType, Arguments >::basicCall(), glbinding::Before, glbinding::createValues(), glbinding::logging::log(), glbinding::Logging, and glbinding::Parameters.
template<typename... Arguments> void glbinding::FunctionHelper< void, Arguments... >::basicCall (const glbinding::Function< void, Arguments... > * function, Arguments &&... arguments) const inline
The documentation for this struct was generated from the following file:
Function.hpp